spring:
  profiles:
    active: dev
  application:
    name: search-admin-be
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 5000
      max-lifetime: 1800000
      pool-name: SearchAdminPool
      leak-detection-threshold: 30000
  jpa:
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  aws:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    region: ap-northeast-2
    dictionary:
      ec2-instance-ids: ${AWS_DICTIONARY_EC2_INSTANCE_IDS}

openai:
  api:
    key: ${OPENAI_API_KEY}
    url: https://api.openai.com/v1/chat/completions
    model: gpt-5-nano
    connect-timeout-ms: 8000
    read-timeout-ms: 45000
    max-retries: 10
    initial-backoff-ms: 1000

upstage:
  api:
    key: ${UPSTAGE_API_KEY}
    embedding:
      url: https://api.upstage.ai/v1/solar/embeddings
  embedding:
    query-model: solar-embedding-1-large-query
    document-model: solar-embedding-1-large-passage
    dimension: 4096
evaluation:
  llm:
    batch-size: 10
    worker-threads: 10

llm:
  queue:
    worker-threads: 10

indexing:
  max-documents: ${INDEXING_MAX_DOCUMENTS:100000}
  batch-size: ${INDEXING_BATCH_SIZE:200}
  max-concurrent-batches: ${INDEXING_MAX_CONCURRENT:8}