spring:
  application:
    name: search-admin-be
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 600000
      pool-name: SearchAdminPool
      leak-detection-threshold: 60000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  elasticsearch:
    host: ${ELASTICSEARCH_HOST}
    port: ${ELASTICSEARCH_PORT}
  aws:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    region: ap-northeast-2
    dictionary:
      ec2-instance-ids: ${AWS_DICTIONARY_EC2_INSTANCE_IDS}
  deployment:
    application-path: /home/ec2-user/search-admin-be
    git-branch: ${GIT_BRANCH:main}
  log-generator:
    enabled: ${LOG_GENERATOR_ENABLED:false}
    events-per-second: ${LOG_GENERATOR_EPS:10}

openai:
  api:
    key: ${OPENAI_API_KEY}
    url: https://api.openai.com/v1/chat/completions
    embedding: https://api.openai.com/v1/embeddings
    connect-timeout-ms: 8000
    read-timeout-ms: 45000
    max-retries: 10
    initial-backoff-ms: 1000
  
logging:
  level:
    com.yjlee.search: DEBUG

evaluation:
  llm:
    batch-size: 10
    worker-threads: 20
generation:
  query:
    batch-size: 20

thread-pool:
  central:
    core-size: 40
    max-size: 50
    queue-capacity: 1000
    keep-alive-seconds: 60

embedding:
  cache:
    max-size: 1000  # 임베딩 캐시 최대 크기