spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/search_admin
    username: search_admin
    password: search_admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

app:
  elasticsearch:
    host: localhost
    port: 9200
  log-generator:
    enabled: false
    parallel-llm-count: 3

logging:
  level:
    com.yjlee.search: DEBUG
    org.springframework: INFO
    org.elasticsearch: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
      environment: dev
  health:
    elasticsearch:
      enabled: false

elastic:
  apm:
    enabled: false