name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Code formatting check
        run: ./gradlew spotlessCheck

      - name: Build application
        run: ./gradlew bootJar

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar
          retention-days: 1

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy via SSM
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "${{ secrets.EC2_INSTANCE_IDS }}" \
            --document-name "AWS-RunShellScript" \
            --parameters '{
              "commands": [
                "sudo -u ec2-user bash -c '\
                  cd /home/ec2-user/search-admin-be && \
                  echo \"최신 코드 가져오기...\" && \
                  git pull origin main && \
                  echo \"Gradle 빌드 시작...\" && \
                  ./gradlew clean bootJar && \
                  echo \"Docker 컨테이너 재시작...\" && \
                  docker compose down && \
                  echo \"이전 Docker 이미지 정리...\" && \
                  docker image prune -f && \
                  echo \"새 Docker 이미지 빌드...\" && \
                  docker build -t search-admin-be:latest . && \
                  docker compose up -d && \
                  echo \"헬스체크 대기중...\" && \
                  sleep 30 && \
                  curl -f http://localhost:8080/actuator/health || exit 1 && \
                  echo \"배포 완료!\"\
                '"
              ]
            }' \
            --timeout-seconds 1200 \
            --output text --query "Command.CommandId")

          echo "Deployment started (ID: $COMMAND_ID)"

          for i in {1..180}; do
            STATUS=$(aws ssm get-command-invocation \
              --command-id $COMMAND_ID \
              --instance-id "${{ secrets.EC2_INSTANCE_IDS }}" \
              --query "Status" --output text 2>/dev/null || echo "Pending")

            case $STATUS in
              Success)
                echo "✅ Deployment successful!"
                exit 0 ;;
              Failed|Cancelled|TimedOut)
                echo "❌ Deployment failed: $STATUS"
                aws ssm get-command-invocation \
                  --command-id $COMMAND_ID \
                  --instance-id "${{ secrets.EC2_INSTANCE_IDS }}" \
                  --query "StandardErrorContent" --output text
                exit 1 ;;
            esac

            [ $((i % 12)) -eq 0 ] && echo "⏳ Still deploying... ($((i/12)) minutes)"
            sleep 5
          done

          echo "❌ Deployment timeout (15 minutes)"
          exit 1
