name: Java CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Ensure gradlew is executable
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --no-daemon -x test
      - name: Run unit/fast tests only
        run: ./gradlew test --no-daemon --exclude-tag integration