name: PR Check

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Code formatting check
        run: ./gradlew spotlessCheck
      
      - name: Compile
        run: ./gradlew compileJava
